### PR TITLE
Updates for gulp-footer

### PR DESCRIPTION
**Pull request by tracker1**
* Update dependencies for
https://github.com/gulp-community/gulp-footer/issues/14
* Swap mocha for jest, easier coverage output
* Add github workflow for test and publish (remove travis.yml)
* Add coverage to gitignore file
* Fix warnings for deprecated Buffer constructor use.

@contra @phated - you'll need to add an `npm_token` secret on this
project for publish, I've added you both on npm for this package.
You will also need to add this project to coveralls.io (free for
open-source projects) in order for the coverage badge to work.

Checkout/clone the latest master after merge then run one of the
following:

* `npm run publish-major`
* `npm run publish-minor`
* `npm run publish-patch`

### CODE REVIEW

**Comment by phated** [comment]
The plan is to require 2FA on gulp-community so automated releases won't work, unfortunately.

**Comment by zhangchenglin** [comment]
> The plan is to require 2FA on gulp-community so automated releases won't work, unfortunately.

@tracker1

**Comment by zdfowler** [comment]
Not seeing this actually in the npm package - @tracker1  is this something that can be picked up?

**Comment by phated** [comment]
@zdfowler what exactly are you looking for? I just got the update workflow working for gulp-pug and will be applying it to the other gulp-community packages when I have time.

**Comment by phated** [comment]
That CVE doesn't matter unless you are somehow passing un-sanitized user input to your gulp tasks (and that would be actually insane).

**Pull request closed without merging**
